//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUCSTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_goods
    {
        public ref_goods()
        {
            this.data_sales = new HashSet<data_sales>();
        }
    
        public int id { get; set; }
        public int code { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<data_sales> data_sales { get; set; }
    }
}
